// export const gamingLaptops = [
//     {
//       brand: "Example Brand",
//       model: "Example Model 1",
//       processor: "Intel Core i7",
//       graphicsCard: "NVIDIA GeForce RTX 3080",
//       ram: "16GB",
//       storage: "1TB SSD",
//       displaySize: "15.6 inches",
//       price: "$2000",
//     },
//     {
//       brand: "Example Brand",
//       model: "Example Model 2",
//       processor: "AMD Ryzen 9",
//       graphicsCard: "AMD Radeon RX 6800M",
//       ram: "32GB",
//       storage: "2TB SSD",
//       displaySize: "17.3 inches",
//       price: "$2500",
//     },
//     {
//       brand: "Example Brand",
//       model: "Example Model 3",
//       processor: "Intel Core i9",
//       graphicsCard: "NVIDIA GeForce RTX 3070",
//       ram: "32GB",
//       storage: "1TB SSD",
//       displaySize: "15.6 inches",
//       price: "$3000",
//     },

//     {
//         brand: "Example Brand",
//         model: "Example Model 3",
//         processor: "Intel Core i9",
//         graphicsCard: "NVIDIA GeForce RTX 3070",
//         ram: "32GB",
//         storage: "1TB SSD",
//         displaySize: "15.6 inches",
//         price: "$3000",
//       },
//   ];